### ISSUE TITLE
Switching between Java/Scala tabs loses scroll position

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-paradox#11]
For example, go to http://doc.akka.io/docs/akka/current/scala/dispatchers.html, scroll part way through the document, and click one of the "Java" tabs. It jumps you back to the top of the page.

I guess the problem is here: https://github.com/akka/akka-paradox/blob/be990951c85a9ab3121d821e0ff05fe837125367/theme/src/main/assets/js/page.js#L34-L42

I think the only way to fix it would be to use the `history.pushState` API https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by raboof** [comment]
You are, of course, completely right.

The eventual fix for this will be to remove that URL switching code you referred to, and do the 'switching' entirely client-side without a page refresh. #10 makes that possible.

**Comment by richardimaoka** [comment]
#10 is merged so this issue to be closed?

**Comment by raboof** [comment]
I guess it is: this now indeed works nicely on Chrome, but on Firefox it doesn't work reliably for me. It's unclear to me whether that's possible to fix, so let's close this particular issue for now. If anyone knows what we can do to make this work across more browsers feel free to reopen of course ;)
