### ISSUE TITLE
Migrate to Google Analytics 4

### ISSUE THREAD

**Issue by octonato** [akka/akka-paradox#194]
We got a notification from Google Analytics that we need to migrate our tracking id to the new Google Analytics 4. 

I initiated the process by creating a new tracking id based on the previous one. 

The next step is to update the docs to use the new tracking. 

For that, akka-paradox must include the following snippet instead:

```javascript
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4TWH1Q5Q3Z"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4TWH1Q5Q3Z');
</script>
```

The ID itself can be deferred to each project site as it is now.

**Comment by rasummer** [comment]
I can take this on, as I'd like to move the new GA4 scripts into Google Tag Manager, which then will allow us to update and extend tracking in the future without needing to republish the docs. I also need to update some of the other tracking in the [Analytics File](https://github.com/akka/akka-paradox/blob/main/theme/src/main/assets/analytics.st), as it's old and out of date
