### ISSUE TITLE
bullet indent is rendered wrong

### ISSUE THREAD

**Issue by patriknw** [akka/akka-paradox#2]
Example:

```
* During normal operation, a circuit breaker is in the *Closed* state:

    - Exceptions or calls exceeding the configured *callTimeout* increment a failure counter
    - Successes reset the failure count to zero
    - When the failure counter reaches a *maxFailures* count, the breaker is tripped into *Open* state
  
* While in *Open* state:

    - All calls fail-fast with a `CircuitBreakerOpenException`
    - After the configured *resetTimeout*, the circuit breaker enters a *Half-Open* state
```

Seems to generate correct html ul and li tags, but there is a "blank line" in front of the 2nd level bullet

**Comment by pvlugter** [comment]
This is a combination of the markdown and the styling. The markdown above, which includes the spaces, will generate paragraph `<p>` tags which are styled with a `margin-bottom`, to create the regular paragraph spacing.

If there are no spaces in the markdown for a list, then `<p>` tags are not generated:

```
* During normal operation, a circuit breaker is in the *Closed* state:
    - Exceptions or calls exceeding the configured *callTimeout* increment a failure counter
    - Successes reset the failure count to zero
    - When the failure counter reaches a *maxFailures* count, the breaker is tripped into *Open* state
* While in *Open* state:
    - All calls fail-fast with a `CircuitBreakerOpenException`
    - After the configured *resetTimeout*, the circuit breaker enters a *Half-Open* state
```

To fix the styling for spaced/paragraphed lists we can add a `margin-top` to these as well, so that if it's spaced in the markdown then it's spaced in the html (and won't look odd like now), and if it's not spaced in the markdown then it's not spaced in the html. We can also remove all spacing from paragraphs in lists, but then there's no way to have styled multi-paragraph lists if you did want to.

**Comment by pvlugter** [comment]
Added a simple styling tweak here:

https://github.com/akka/akka-paradox/pull/1/commits/9e1451c864d0488b108e7f96dbf7b2f6a394b5c6

This just has spacing for both top and bottom of paragraphs in lists. This means that if there are line breaks in the markdown source, there will be space in the styled html.

For example, current markdown:

```
* During normal operation, a circuit breaker is in the *Closed* state:

    - Exceptions or calls exceeding the configured *callTimeout* increment a failure counter
    - Successes reset the failure count to zero
    - When the failure counter reaches a *maxFailures* count, the breaker is tripped into *Open* state
  
* While in *Open* state:

    - All calls fail-fast with a `CircuitBreakerOpenException`
    - After the configured *resetTimeout*, the circuit breaker enters a *Half-Open* state
```

produces

<img width="717" alt="list-1" src="https://cloud.githubusercontent.com/assets/59895/25982002/039156ae-372d-11e7-9483-32b4c7d7851a.png">

Without line breaks in the markdown:

```
* During normal operation, a circuit breaker is in the *Closed* state:
    - Exceptions or calls exceeding the configured *callTimeout* increment a failure counter
    - Successes reset the failure count to zero
    - When the failure counter reaches a *maxFailures* count, the breaker is tripped into *Open* state
* While in *Open* state:
    - All calls fail-fast with a `CircuitBreakerOpenException`
    - After the configured *resetTimeout*, the circuit breaker enters a *Half-Open* state  
```

produces

<img width="713" alt="list-2" src="https://cloud.githubusercontent.com/assets/59895/25982013/15f322dc-372d-11e7-9b1d-9a14aaf4f8ee.png">

With line breaks throughout:

```
* During normal operation, a circuit breaker is in the *Closed* state:

    - Exceptions or calls exceeding the configured *callTimeout* increment a failure counter

    - Successes reset the failure count to zero

    - When the failure counter reaches a *maxFailures* count, the breaker is tripped into *Open* state

* While in *Open* state:

    - All calls fail-fast with a `CircuitBreakerOpenException`

    - After the configured *resetTimeout*, the circuit breaker enters a *Half-Open* state  
```

produces

<img width="717" alt="list-3" src="https://cloud.githubusercontent.com/assets/59895/25982020/25c7c38e-372d-11e7-9e58-978c2ddc5804.png">

**Comment by patriknw** [comment]
excellent, that looks perfect

btw, do you know why 4 spaces are needed, I thought 2 would be enough?

**Comment by pvlugter** [comment]
Yeah, I think indentation for nested lists is one of those things in markdown that varies quite a bit between implementations. While I think reStructuredText allows any number of spaces for nesting and github markdown allows 2 spaces, I think pegdown follows the more traditional indent of tab or 4 spaces (which was only implied in the original markdown spec?). 4 spaces is probably best to use in markdown to work with the various implementations.

**Comment by pvlugter** [comment]
There's babelmark for comparing markdown implementations:

http://johnmacfarlane.net/babelmark2/

**Comment by pvlugter** [comment]
http://johnmacfarlane.net/babelmark2/faq.html#lists
