### ISSUE TITLE
Update from version 0.3.0 to 0.3.2 Paradox to fix URL Encoding Issue

### ISSUE THREAD

**Issue by fringedgentian** [akka/akka-paradox#20]
The fiddles (such as in the middle of this page: https://doc.akka.io/docs/akka/2.5.4/scala/stream/stream-quickstart.html#stream-quickstart) don't work because of URL encoding issue that was fixed in Paradox 0.3.2:

https://github.com/lightbend/paradox/releases/tag/v0.3.2

**Comment by ktoso** [comment]
Thanks for reporting, that's an old docs page -- it seems that the current version works fine: https://doc.akka.io/docs/akka/current/stream/stream-quickstart.html?language=scala#stream-quickstart

(current akka is 2.5.8)

I guess this can be seen as need for reviving the "box that shows you that you're not on the latest version of the docs".

**Comment by raboof** [comment]
I think that one was updated manually - https://doc.akka.io/docs/akka/snapshot/stream/stream-quickstart.html?language=scala#stream-quickstart indeed still has the problem.

**Comment by ktoso** [comment]
Oh I missed that one -- the first on the page I saw worked so thought it's fixed.
Thanks for updating @raboof :)

**Comment by ktoso** [comment]
Should we release today so this is included in tomorrows release, could you help with that @raboof ?

**Comment by raboof** [comment]
Hmm I created the 0.6 tag and travis should do the rest, but it failed to upload:
```
[info] Done packaging.
[info] 	published sbt-paradox-akka to com.lightbend.akka/sbt-paradox-akka/scala_2.12/sbt_1.0/0.6/jars/sbt-paradox-akka.jar
[info] 	published sbt-paradox-akka to com.lightbend.akka/sbt-paradox-akka/scala_2.12/sbt_1.0/0.6/srcs/sbt-paradox-akka-sources.jar
[info] 	published sbt-paradox-akka to com.lightbend.akka/sbt-paradox-akka/scala_2.12/sbt_1.0/0.6/docs/sbt-paradox-akka-javadoc.jar
[info] 	published ivy to com.lightbend.akka/sbt-paradox-akka/scala_2.12/sbt_1.0/0.6/ivys/ivy.xml
[info] akka/sbt-paradox-akka@0.6 was released
java.lang.RuntimeException: error uploading to https://api.bintray.com/maven/akka/maven/maven/com/lightbend/akka/paradox-theme-akka/0.6/paradox-theme-akka-0.6.pom: {"message":"Unable to upload files: An artifact with the path 'com/lightbend/akka/paradox-theme-akka/0.6/paradox-theme-akka-0.6.pom' already exists"}
	at bintray.BintrayMavenRepository.put(Resolver.scala:27)
```
Weird... removing from bintray and trying again

**Comment by raboof** [comment]
(looks like it was updated fine)
