### ISSUE TITLE
Build tool showing up as dropbox in sidebar

### ISSUE THREAD

**Issue by johanandren** [akka/akka-paradox#208]
Is ok:ish for the docs not having a search box, but in those with search box it pushes it out of the dark blue background:

<img width="335" alt="Screenshot 2023-10-25 at 16 53 35" src="https://github.com/akka/akka-paradox/assets/666915/2505bd36-c040-4751-99b2-c212a5b5bba0">

I think best would be if we could _not_ make a dropbox for build tool at all somehow

**Comment by johanandren** [comment]
Manually worked around by making that background 220px for Akka and Akka HTTP docs directly on docserver for now (waiting for CDN to propagate)

**Comment by patriknw** [comment]
I agree, good finding

**Comment by ennru** [comment]
Fixed in the template with
- #213
