### ISSUE TITLE
Styling for "Full source at GitHub" links

### ISSUE THREAD

**Issue by ennru** [akka/akka-paradox#36]
It is now possible to style these links via CSS.
Any suggestion on how to make them a bit less prominent?

**Comment by patriknw** [comment]
Thanks, that was my first impression of all those links.

Perhaps a small icon somewhere (upper right corner) would be enough?

**Comment by 2m** [comment]
We could style it as an "external link" icon that appears in the same style as "anchor link" icon for the paragraphs.

![2018-10-01-101617_932x386_scrot](https://user-images.githubusercontent.com/422086/46297802-3071d200-c563-11e8-99f7-bc34235b6317.png)

**Comment by patriknw** [comment]
sounds good

**Comment by ennru** [comment]
I'd say that is too invisible. Maybe a Github icon would indicate what's there?

**Comment by 2m** [comment]
We could have that icon visible all the time, not only on hover.

**Comment by patriknw** [comment]
and doesn't have to mention "at GitHub"

**Comment by ennru** [comment]
@johanandren Can you PR that, please?
The text comes from Paradox, best would be to change it there or to make it configurable.

**Comment by 2m** [comment]
So it looks like there is [no UTF-8 icon for that](https://stackoverflow.com/questions/1899772/new-window-icon-for-web-accessibility). :/

What about this?

![2018-10-02-085921_1007x440_scrot](https://user-images.githubusercontent.com/422086/46353355-90c74900-c621-11e8-801a-4da45f1af501.png)

I also think we should make this change in the generic theme as well.

**Comment by raboof** [comment]
Looks nice! So does the link target change based on which tab is selected?

**Comment by 2m** [comment]
Created a PR for the generic theme: https://github.com/lightbend/paradox/pull/260
