### ISSUE TITLE
bintrayRelease

### ISSUE THREAD

**Issue by raboof** [akka/akka-paradox#7]
The logs suggest there's a `bintrayRelease` sbt task - should we add that to travis instead of manually logging into the bintray website?

**Comment by 2m** [comment]
We should set `bintrayReleaseOnPublish in ThisBuild := true` (which is the default) here https://github.com/akka/akka-paradox/blob/35dc7a00775dec581a933ac1fa1964593d818fc1/project/Publish.scala#L12
