### ISSUE TITLE
Margins center main content

### ISSUE THREAD

**Issue by ennru** [akka/akka-paradox#70]
Something with the changed margins doesn't work correctly for "short" pages.

Examples:
https://doc.akka.io/docs/akka-grpc/current/overview.html#grpc

Or from a local preview:

![bild](https://user-images.githubusercontent.com/458526/63105547-4f156780-bf81-11e9-9ecf-a90d92cb5f7c.png)

@rasummer

**Comment by rasummer** [comment]
For https://doc.akka.io/docs/akka-grpc/current/overview.html I can't reproduce, it appears fine for me on Chrome and FF (mac). 

![Screen Shot 2019-08-15 at 8 32 58 AM](https://user-images.githubusercontent.com/1418129/63106585-fd94ba80-bf37-11e9-84dd-6ce47a0b583d.png)

Also once a screen is very wide it will center itself. However we shouldn't be seeing the gap above the content. 

I will fire up Akka enhancements locally to test, is it the same process as the others to get it running locally?

**Comment by rasummer** [comment]
Also are you using a screen that is rotated, so that the screen is taller than it is wide?

**Comment by johanandren** [comment]
Check this page instead, that is short and gets auto margins top and bottom: https://doc.akka.io/docs/akka-grpc/current/buildtools/index.html

**Comment by johanandren** [comment]
Ah, we figured it out, you need 4-5k screen to see it, laptop screen will not be tall enough.

**Comment by rasummer** [comment]
OK, so there is actually an auto margin on top and bottom for the `.fixed-shift-for-large` class. I can fix this and then it should work on all screens, including large ones :)
