### ISSUE TITLE
wrong z-index for search results?

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-paradox#76]
<img width="643" alt="Screen Shot 2019-08-28 at 15 50 56" src="https://user-images.githubusercontent.com/762126/63861798-da442380-c9ab-11e9-8b87-39093b25d52a.png">

Today I started noticing the cosmetic issue above where the search results dialog is displayed behind the tables of contents.

**Comment by johanandren** [comment]
Also noted in https://github.com/akka/akka.github.com/issues/632

**Comment by ignasi35** [comment]
losing this in favour of akka/akka.github.com#632
